### ISSUE TITLE
Move new search input to be right aligned

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#108]
In https://github.com/ember-learn/guidemaker-ember-template/pull/107 we have a wonderful new search design 😍 One improvement I would like to make is to actually right-align the search bar

This is similar to what is currently happening in the live guides: 

![Image](https://user-images.githubusercontent.com/594890/183105780-f52e7def-24cd-494e-a9ed-7628fb3a831b.png)

I didn't want to block the previous PR because a) it's awesome and needed to be merged instantly!! and b) this work might need to be done in the ember-styleguide repo 🤔 not 100% sure on that one

**Comment by MinThaMie** [comment]
Also to fix: overflow of the blue color of the "title"

The tether positioning makes it difficult. We've two options:
1. Move the tether to tether `right` and for mobile make it full width results
2. Move the tether to `right` for normal screens and `left` for mobile screens

![Image](https://user-images.githubusercontent.com/5811560/183135095-cecea072-92af-4904-9926-71d0a7c25573.png)

**Comment by mansona** [comment]
Tether position is a JavaScript thing right? Or can we do it in CSS? The reason I ask is because I am not a fan of JS based "media queries"

**Comment by mansona** [comment]
This is done and can be seen on the tracker branch for the guides update: https://deploy-preview-1717--ember-guides.netlify.app/release/ 🎉
