### ISSUE TITLE
Investigate if there is still a slowdown in mobile safari

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#15]
In the old application, there was a PR that tried to fix a rendering slowdown in mobile safari due to strange compositing errors. 

We should investigate if this is still the case and if so then we should consider porting https://github.com/ember-learn/guides-app/pull/216 to this repo

**Comment by IgnaceMaes** [comment]
Going to close this issue as it's been five years. Most likely this has been fixed by either all the design changes that have been done, or by modern browsers being more optimized.

If this would still be an problem, let's reopen a new issue.
