### ISSUE TITLE
Width of the content as discussed in the discord thread + stickiness sidepanels

### ISSUE THREAD

**Issue by MinThaMie** [ember-learn/guidemaker-ember-template#152]
Width of left menu can become 300

Center content text can be 800px (WCAG 1.4.8 AAA is 80 characters max)

Maybe make the "on this page" stick to the content instead of the moving all the way to the right

**Comment by MelSumner** [comment]
just a reminder that we're going for AA, but guides are usually easier to read if they are not the full width of the page. :) What do other guides do that are easy to read? Maybe that's a nice comparison point.

**Comment by MinThaMie** [comment]
@MelSumner we could not find if there was an AA guideline, the only one present seemed to be AAA. Other guides are at a similar width, between 850 - 1050.
