### ISSUE TITLE
Remove the use of jQuery in guides-article

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#16]
in the old guides-app there was a WIP PR to remove the use of jQuery in the guides-article https://github.com/ember-learn/guides-app/pull/242

### Todo 

- [ ] investigate if this work is still needed (i.e. check if it has already been done)
- [ ] re-implement the work removing jQuery

**Comment by jbryson3** [comment]
This appears to be already done with https://github.com/ember-learn/guidemaker-ember-template/commit/b3f88ebe0b79f3c97d019598ad193c7344013a1d

**Comment by IgnaceMaes** [comment]
Looks like this was implemented, indeed!
