### ISSUE TITLE
Add CSS styling for tables

### ISSUE THREAD

**Issue by IgnaceMaes** [ember-learn/guidemaker-ember-template#192]
Currently tables are unstyled in the guides. Some CSS should be written for the `table` element so it looks nicer.

<img width="310" alt="image" src="https://github.com/ember-learn/guidemaker-ember-template/assets/10243652/cd2aea19-445b-4e1f-8f61-7f6d73a68752">

**Comment by Ziphozenkosimthombe** [comment]
can I take that?

**Comment by IgnaceMaes** [comment]
Feel free to give it a go!

Some extra details:
- The styleguide should be used for color and spacing variables: https://ember-styleguide.netlify.app/concepts/colors/
- An example of a table should be added to a markdown file in the test app so this can be revieed.
- There is no design ready to follow. I think it would be nice to make the table full width. Try to make it fit in with the rest of the page.

**Comment by Ziphozenkosimthombe** [comment]
if I ask the table I should add it to the test-app folder inside the readme file? can you please give me more guidance on that.

**Comment by ArunPragadeeswar007** [comment]
@IgnaceMaes  please review this [PR](https://github.com/ember-learn/guidemaker-ember-template/pull/198)
