### ISSUE TITLE
Write out READMEs

### ISSUE THREAD

**Issue by IgnaceMaes** [ember-learn/guidemaker-ember-template#193]
It looks like we lose some of the content of our README descriptions in the v2 addon conversion. (https://github.com/ember-learn/guidemaker-ember-template/pull/188)

The template in the root `README.md` should be completed with extra info on what this addon does.

**Comment by raspberri05** [comment]
Hi i can work on this issue

**Comment by mansona** [comment]
This was fixed in https://github.com/ember-learn/guidemaker-ember-template/pull/201
