### ISSUE TITLE
Problem updating ember-auto-import

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guidemaker-ember-template#22]
` TypeError: (0 , _algoliasearch.default) is not a function`

See https://github.com/ember-learn/guides-source/issues/914

**Comment by jenweber** [comment]
PR https://github.com/ember-learn/guidemaker-ember-template/pull/23

**Comment by IgnaceMaes** [comment]
Looks like this was fixed in a different PR. Closing this issue to clean up older GitHub issues.

If it would still be a problem feel free to open a new issue.
