### ISSUE TITLE
Add tests 🙏

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/guidemaker-ember-template#26]
The custom services and components authored here should absolutely have some tests. Without them, it is very very hard to evaluate changes like #25 to see if all the supported use cases are handled.

The following components should be tested:

- [ ] `addon/components/dropdown-header.js`
- [ ] `addon/components/search-input.js`
- [ ] `app/components/chapter-links.js`
- [ ] `app/components/guides-article.js`
- [ ] `app/components/info-banner.js`
- [ ] `app/components/link-to.js`
- [ ] `app/components/search-result.js`
- [ ] `app/components/table-of-contents.js`

**Comment by mum-never-proud** [comment]
@rwjblue I would love to write tests for these if not done already

**Comment by MinThaMie** [comment]
Everything in the template is covered by Percy, so we don't need this to happen. So I'm closing it :)
