### ISSUE TITLE
Design an approach for the search dropdown in the Guides

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#41]
Here is the current implementation: <img width="1440" alt="Screenshot 2020-03-30 18 18 30" src="https://user-images.githubusercontent.com/604117/77967381-fe097800-72b2-11ea-8989-411f74a12ab3.png">

Note: the new design must have "Search by Algolia" as we have a sponsored account

Note we need a design for all aspects of the search dropdown (empty state, loading state etc) 

If anyone wants to work with the HTML on this I have opened a branch on `guidemaker-ember-template` called `algolia-tests` that we can use the "pauseTest() method" to easily get back to the same place. 

https://github.com/ember-learn/guidemaker-ember-template/blob/algolia-tests/tests/acceptance/search-test.js#L15-L16

For reference the "pauseTest() method" is to run the test locally and put it in `Development mode` so you can change files and you get back to having the dropdown open again without having to click 👍

**Comment by MinThaMie** [comment]
The design is done and the code committed to the branch :)

<img width="1176" alt="Screenshot 2022-08-05 at 14 51 44" src="https://user-images.githubusercontent.com/5811560/183085087-6c1e2181-ebd6-4030-8d1b-7411e64f29a9.png">
<img width="1219" alt="Screenshot 2022-08-05 at 14 51 51" src="https://user-images.githubusercontent.com/5811560/183085096-3a0b48d2-335d-4a5b-86d9-d97f57831961.png">

**Comment by mansona** [comment]
merged in https://github.com/ember-learn/guidemaker-ember-template/pull/107
