### ISSUE TITLE
Add more example uses to the dummy app

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guidemaker-ember-template#66]
## Description

Our goal is to make it so that you can work in guidemaker-ember-template and be confident that when it is used in the guides, things will look good.

If you run the addon locally (`npx ember serve`) you will see the dummy app, which needs more examples.

To-do:
- add examples to guidemaker-ember-template dummy app so that we have full coverage on features that the Ember guides needs
    - LTS versions
    - Code blocks
    - Anything else???
- make sure all examples are represented in Percy tests

**Comment by mansona** [comment]
This was fixed in #72 🎉
