### ISSUE TITLE
move the pagination from the blog design to the styleguide

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#75]
https://github.com/ember-learn/empress-blog-ember-template/blob/master/addon/components/pagination.hbs

make it so that it can work for the blog and the guides at the same time

consider "borrowing" the animation implementation from https://guides.emberjs.com/release/getting-started/

**Comment by prakashchoudhary07** [comment]
I'd like to take this up. Will send out a PR by next week.

**Comment by mansona** [comment]
@prakashchoudhary07 thanks for taking this one! I've moved the task into "in progress" because you're looking at it. Let me know if you have any questions 👍

**Comment by mansona** [comment]
Hey @prakashchoudhary07 how are you getting on with this issue? do you need any help with it?

**Comment by prakashchoudhary07** [comment]
Hey @mansona I have raised a WIP PR, please have a look [here](https://github.com/ember-learn/ember-styleguide/pull/406)

**Comment by prakashchoudhary07** [comment]
@mansona Please review the WIP PR :smiley:
