### ISSUE TITLE
Improve the design of the ToC sidebar

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#85]
In https://github.com/ember-learn/guidemaker-ember-template/pull/80 we are adding an initial design for the sidebar that is an improvement to what is currently there (no design at all) but doesn't live up to the high quality design that the overall redesign has been able to achieve.

We should consider how to improve the design of the sidebar and make it look and feel more slick before releasing the new Guidemaker template 👍 

## To do

- [ ] Make sure that the color contrast of the text on background still passes AA WCAG
  - in #80 we added a background color behind the currently active ToC item which makes that text fail 🙈

**Comment by MinThaMie** [comment]
After a discussion with @mansona we've decided to go for a simpler style, that steals from the old side menus making a separate thing, like on ember-cli-addon-docs. We'll find a way to give it some pasazzz.

**Comment by mansona** [comment]
This was fixed in https://github.com/ember-learn/guidemaker-ember-template/pull/98 

Any further improvements will be iterative 👍
