### ISSUE TITLE
Fix the design for the 404 page

### ISSUE THREAD

**Issue by mansona** [ember-learn/guidemaker-ember-template#86]
If you go to https://website-redesign--guidemaker-ember-template.netlify.app/release/index.html you will see that the styles for our 404 page are not correct

I think we will need to make sure that they are wrapped correctly (in the same way as the main application) and have some decent padding and margins so that it doesn't look strange

**Comment by harshith-venkatesh** [comment]
Greetings @mansona,
I would like to take this issue up.
